### PR TITLE
Add the correct collection - Traditional Chinese 999

### PR DESCRIPTION
**Pull request by aliffattahfaiz**
The actual traditional chinese number from 000-999. Not the capitalized version of simplified chinese.

### CODE REVIEW

**Comment by aliffattahfaiz** [comment]
Help putting a new pull request for the traditional chinese number to help team with the updating the current "traditional chinese number" that is not really the traditional chinese. Hope this help the team!

**Comment by Ericwang120** [comment]
thx for help to list bro

**Comment by aliffattahfaiz** [comment]
Also to add, the former pull request #84 is also correct per se. It is rightfully a 999 chinese number. It's just the number is rather the uppercase simplified, not traditional. So the intention of this update pull request is to provide the traditional chinese numbers that is commonly and officially used by overseas chinese speaker (e.g hongkong, taiwan, macau, etc) in their life, work, official paper, financial statement, etc.

The traditional chinese is established as far as 2nd AD century, and some scripture with traditional chinese has been found during Han dynasty. Now traditional chinese are still being used as artistic work in mainland china.

So it is worth noted that while #84 is also correct, this pull request update is about the traditional number that used by overseas china and originated since 2nd AD century.

**Comment by CryptoGatsu** [comment]
so which tn cn request am i pushing? this one or the one previously submitted.

**Comment by aliffattahfaiz** [comment]
@CryptoGatsu Also the previously submitted is the uppercase of simplified chinese, and this one is the traditional chinese number. This collection is already sold out while the previously submitted is still yet to be sold out

**Comment by f10wers** [comment]
> 

FWIW, the uppercase/capitalized version previously submitted is the more commonly-used version by a very wide margin. The capitalized version is used in all of mainland China where as this version is used more in smaller areas such as Hong Kong and Taiwan.

Both are correct, no fud here. Thank you for all these reviews.

**Comment by aliffattahfaiz** [comment]
I fully understand what you mean by that. Again, capitalized version is used in mainland china because it is simplified china. But then it means we have 2 simplified chinese. Also talking about the population that used it, simplified chinese already cover the mainland china, and traditional chinese are covering hongkong, macau, taiwan, etc. It has different coverage. The goal here is to include every unique organic volume as much as possible.

Also number of population doesn't really matter. Arabic has much much less population than china but the volume on arabic ens is stronger. What matter is how close the culture of the said country to internet, etc. While China has larger population vs every other country, but it has stricter internet policy against crypto.

The point here is that we need representation covering language as much as possible. Simplified already do the job what the capitalied chinese version plan to do

**Comment by Failbringer1** [comment]
> so which tn cn request am i pushing? this one or the one previously submitted.

Totally agree. Capitalized version will be more in demand, because it is used throughout China. But I think you can just add both versions. There will be no confusion when the correct names are given to the collections.
1 - Simplified chinese
2 - Capitalized chinese
3 - Traditional chinese 

In total there will be only 2500 unique names in three versions, for a population of 1.5 billion people.

**Pull request merged**
