### PR TITLE
Add Gambler's Club

### PR DESCRIPTION
**Pull request by Singham1238**

### CODE REVIEW

**Review by tunnckoCore — CHANGES_REQUESTED** [review]
@Singham1238 where's the csv (list of names)? twitter, discord?

sorry can't get "verified", haha.

**Comment by tunnckoCore** [comment]
oh, it's #6 , okay

**Comment by Singham1238** [comment]
Did i do i correctly?

**Comment by tunnckoCore** [comment]
@Singham1238 you can check for some step by step on the #10

**Comment by Singham1238** [comment]
Is it okay now?

**Comment by tunnckoCore** [comment]
@Singham1238 

yea, it's better, thanks.

**Pull request closed without merging**
