### PR TITLE
Add 360 Degree Club Collection

### PR DESCRIPTION
**Pull request by yakphi**
Please add the 360 Degree Club Collection

### CODE REVIEW

**Review by CryptoGatsu — COMMENTED** [review]
looks good to me!

**Review by enstrades — COMMENTED** [review]
Since the club is called "360 degree club" the first row for 000 needs to deleted otherwise 361 number exist. The team has submitted  the original "360 degree club" without the 000 but due to a merge with another submission the 000 was mistakenly added.

**Comment by fright11** [comment]
there should be 361 numbers its 360 degrees not numbers so 000 is a part of the club

**Comment by negro-rekt** [comment]
So, how much time its take to appear the group in ens.domain? Is any way yo accelerate the process?

**Pull request merged**
