### PR TITLE
Add Substances Club

### PR DESCRIPTION
**Pull request by FutureHndrxxx**
As discussed here is my initial list to create the Substances Club on ENS Vision.

Apologies for lack of tokens, tried to run the npm tool but it wouldn't work and couldn't troubleshoot (I suspect permissions issues somewhere on my machine).

Everything else is ready to go, all mandatory fields filled in for metadata, list provided as correctly formatted CSV.

### CODE REVIEW

**Comment by CryptoGatsu** [comment]
this has been sent to main branch!

**Comment by szanuje** [comment]
hey @FutureHndrxxx @CryptoGatsu , I think this PR broke the `ens-collections.json' file.

**Comment by FutureHndrxxx** [comment]
@szanuje looks like that's because the comma after each section was forgotten when it was merged to main, looks like this is fixed in the latest update so hopefully no issues now?

Any ETA on when the category will be added to ENS Vision?

Thank you all for your hard work!

**Comment by FutureHndrxxx** [comment]
@tunnckoCore no logo currently as it was listed as optional. I can whip a lazy one up if it is required.

**Pull request merged**
