### PR TITLE
Add Tolkien collection csv and logo (json already exists)

### PR DESCRIPTION
**Pull request by forzaphil**
There are 7 entries where the tokenId is missing. This is because the tokenId generator has a bug that prevents it from generating a token isf the name has "eth" in it, like Denethor. All of the missing tokens are because of this.

### CODE REVIEW

**Comment by szanuje** [comment]
Hey @forzaphil , you can generate tokenId by yourself easily, the process is the following:
1. Get domain label e.g. `denethor` and calculate keccak256 hash. You can use that https://emn178.github.io/online-tools/keccak_256.html
2. Get the output `keccak256(denethor) = 345d1ebdfa1120be6782e11cb25e7ae615271c9493da9642bb4ceed9b8af20f9` and convert it to decimal value. You an use that https://www.rapidtables.com/convert/number/hex-to-decimal.html
3. Put the output in csv, eg. `tokenId (denethor) = 23684797077509684675161393445568554097740952594248531973855304670722038636793`
Proof that this is valid:
https://opensea.io/assets/ethereum/0x57f1887a8bf19b14fc0df6fd9b2acc9af147ea85/23684797077509684675161393445568554097740952594248531973855304670722038636793

IMO missing tokenId is unacceptable :D

**Comment by forzaphil** [comment]
@szanuje That's great. Thank you.

**Comment by forzaphil** [comment]
All tokenIds have been added and are included in the current version.

**Comment by forzaphil** [comment]
@tunnckoCore  Is there anything else that you need from me for this collection now that all the tokenIds are present?

**Pull request merged**
