### PR TITLE
feat: adding 999-persian-club

### PR DESCRIPTION
**Pull request by super-scary-ghost**
Request to add the 000-999 persian numerals as a club in ens vision.

I believe its necessary to create a separate category for Persian digits considering they are identical to Arabic in real world but with different Unicode, causing confusions for people who wanna invest into just Arabic digits or vica versa.

Some reasons worth mentioning as to why this club should be included:
- Persian language is historically older and more complete than Arabic.
- Both native speakers of each community can 'read' both Arabic and Persian alphabets as they are identical. Creating a category for Persian digits will be extremely helpful to avoid confusion as it's extremely hard for new investors to distinguish.

### CODE REVIEW

**Comment by Remolten** [comment]
I wholeheartedly agree that adding this would be helpful to avoid confusion between the two.

To clarify, the Persian digits 4, 5, and 6 are different from Arabic. In addition, Persian has additional letters in their alphabet that Arabic doesn't have. Though some of the characters are the same, it is an entirely different language.

**Comment by engr-skyang** [comment]
Fully agreed to add persian number as a separate collection. It literally a different language to Arabic.

**Comment by stevenliem7** [comment]
@ensvision arabic and persian are TWO different languages despite sharing common alphabets. Hence there are some similarities with the numbers but they are not 100% the same. Logo could be changed but languages HAVE DIFFERENCES

**Comment by hasher87** [comment]
Persian is an entirely different language than Arabic. Arabic is the official language that is used in the Holy Quran, but the languages of the Persian cannot be applied into reading the Holy Quran because it is totally different world of languages.

By providing a separation of language, this would allow the Persian language (numbers/char) to be visible in the eyes of ENS domain, not just Arabic.

**Comment by yingxiayin** [comment]
AGREE, we need to list this to help ppls know this difference

**Comment by yingxiayin** [comment]
we need to reopen this issue #79

**Comment by kiwi998** [comment]
Im aggre with that too
So many different between arabic and farsi in digits and also letters
Plz confirm that

**Comment by Atomthenft** [comment]
I agree the notion to add it as a separate collection since unicode is different, communities are different and web3 in itself is the space of decentralization and freedom where either of these community can freely connect to members of mutual beliefs and represent their language to the world level even if it's only slight variance in the appearance of alphabets but yet different.

**Comment by talhakilicel** [comment]
۵۵۲ = 552
Persian999 will gain a lot of volume because it is similar with arabic999 but actually they are completely different characters.
Also Persian is not new, they are historical

**Comment by Flodis79** [comment]
Good luck all 🎉🎉🎉

**Pull request merged**
