### PR TITLE
added male and female firstnames

### PR DESCRIPTION
**Pull request by Zimtente**

### CODE REVIEW

**Comment by TransaccionETH** [comment]
Hello I’d like to offer some info on sur names that are included in Forebears information chart. I’ll send the sur name/ last name domain. And Forebears.io info as well 
1B4C2685-3798-4D4C-B9D1-92537FFA10C5
08452546-43C0-409C-BF4B-AC00F7B3802E
1B404402-0D0F-410B-A3E5-BEC9178848F1
08072D3F-F05D-4677-9C1F-BC50243A1DC0
A7921CB1-369B-486C-8A8A-64C6FED6F5AF
186F6C8A-0B0C-45BE-B3D6-8E86EE120B9E
60FADA0A-C4E8-4126-A3CE-A25A3AA11015
C9DCCBE0-CEBB-49AC-A46A-BF67D08CAFA8
189DADFD-DC4E-4215-AEDA-0C9A22A4C559
BE90E538-DD5F-49CD-9098-2B90FA354DC2
D4A8D068-4421-4487-8E50-26329E102CAC
EA96E24F-220D-42AE-8834-A4C92005C7A6

4B1E9A4F-5A65-4843-B3AE-6F138D08543D
E8FB5A3D-F9C0-4FE2-ACA8-5EF332DC09AC
36A8A7C4-DD15-4373-8DB8-5A4F20C02580

Perreira is in the list and not my Pereyra. Which is the most common one. I cou
DFE903C0-827F-4D12-B92D-A9B7822FFB1D
ldnt 

87DB7B5A-887B-461F-8235-C138E509E5F1
11CDFE58-1577-4A9E-8BEF-7B6E0BB24199
72E2BDB4-5565-4AA1-AEDA-D30F69005224

AB2DFE40-0A54-4E06-8553-DBA3CE0F5296

**Comment by TransaccionETH** [comment]
Also, I put myself out there for any help on names or sur names from the Hispanic community. As we are growing day by day. And would love to be included here. I can research some names on a daily basis and update info, forebears.io info and so on. Please let me know if I can help.

**Comment by domininft** [comment]
Explanation why the item should be added from a collection: first names
Collection Name: Male first Names
Name of the items: antonello.eth, filippo.eth fiorello.eth and eolo.eth

Collection Name: Female first Names
Name of the items: letizia.eth and raffaella.eth

**Comment by TransaccionETH** [comment]
Forebears.io

**Comment by TransaccionETH** [comment]
Hello any updates?

**Pull request merged**
